#include <gtest/gtest.h>

#include "quantModeling/engines/analytic/heston_cos.hpp"
#include "quantModeling/market/heston_calibration.hpp"
#include "quantModeling/models/equity/sabr.hpp"

#include <cmath>
#include <vector>

namespace quantModeling
{
    namespace
    {
        const HestonParams kTruth{/*v0=*/0.03, /*kappa=*/2.5, /*theta=*/0.05,
                                  /*xi=*/0.6, /*rho=*/-0.7};
        constexpr Real kSpot = 100.0, kRate = 0.03, kDiv = 0.01;

        /// A surface generated by Heston itself: the implied vol of the COS
        /// price at each (K, T). A calibration must find its way back.
        std::vector<HestonCalibrationQuote> heston_surface(const HestonParams &p)
        {
            std::vector<HestonCalibrationQuote> quotes;
            for (const Real T : {0.1, 0.25, 0.5, 1.0, 2.0})
            {
                const Real F = kSpot * std::exp((kRate - kDiv) * T);
                const Real df = std::exp(-kRate * T);
                for (const Real z : {-2.0, -1.0, -0.5, 0.0, 0.5, 1.0})
                {
                    const Real K = F * std::exp(z * 0.2 * std::sqrt(T));
                    const Real call = heston_cos_price(F, K, T, df, p, true);
                    quotes.push_back({K, T, black76_implied_vol(call, F, K, T, df), 1.0});
                }
            }
            return quotes;
        }
    } // namespace

    TEST(HestonCOS, TheBatchedPricerMatchesTheSingleStrikeOneExactly)
    {
        const Real F = 105.0, T = 0.75, df = 0.97;
        const std::vector<Real> strikes{70.0, 95.0, 105.0, 130.0};
        for (const bool is_call : {true, false})
        {
            const std::vector<Real> batch = heston_cos_prices(F, strikes, T, df, kTruth, is_call);
            for (std::size_t i = 0; i < strikes.size(); ++i)
                EXPECT_NEAR(batch[i], heston_cos_price(F, strikes[i], T, df, kTruth, is_call), 1e-12);
        }
    }

    TEST(HestonCalibration, RecoversTheParametersThatGeneratedTheSurface)
    {
        const HestonCalibration fit = calibrate_heston(heston_surface(kTruth), kSpot, kRate, kDiv);

        EXPECT_EQ(fit.n_quotes, 30u);
        EXPECT_EQ(fit.n_maturities, 5u);
        EXPECT_EQ(fit.n_unpriced, 0u);
        // The fit itself, in vol points: a hundredth of a vol point.
        EXPECT_LT(fit.iv_rmse, 1e-4);
        EXPECT_LT(fit.iv_worst, 5e-4);
        // The parameters: v0, theta and rho are well identified by a smile
        // term structure; kappa and xi trade off along a flat valley, so they
        // get a looser band.
        EXPECT_NEAR(fit.params.v0, kTruth.v0, 1e-3);
        EXPECT_NEAR(fit.params.theta, kTruth.theta, 3e-3);
        EXPECT_NEAR(fit.params.rho, kTruth.rho, 0.03);
        EXPECT_NEAR(fit.params.kappa, kTruth.kappa, 0.5);
        EXPECT_NEAR(fit.params.xi, kTruth.xi, 0.1);
    }

    TEST(HestonCalibration, AFlatSurfaceGivesAFlatFitWithLittleVolOfVol)
    {
        // Property: a surface with no smile and no term structure is best
        // matched by a Heston with next to no randomness in the variance --
        // xi pinned near its lower bound, v0 = theta = the flat variance.
        std::vector<HestonCalibrationQuote> flat;
        for (const Real T : {0.25, 0.5, 1.0})
            for (const Real K : {85.0, 100.0, 115.0})
                flat.push_back({K, T, 0.25, 1.0});

        const HestonCalibration fit = calibrate_heston(flat, kSpot, kRate, kDiv);
        EXPECT_LT(fit.iv_rmse, 2e-3);
        EXPECT_NEAR(std::sqrt(fit.params.v0), 0.25, 0.01);
        EXPECT_NEAR(std::sqrt(fit.params.theta), 0.25, 0.01);
        EXPECT_LT(fit.params.xi, 0.2);
    }

    TEST(HestonCalibration, RejectsAnEmptyOrMalformedSurface)
    {
        EXPECT_THROW(calibrate_heston({}, kSpot, kRate, kDiv), InvalidInput);
        EXPECT_THROW(calibrate_heston({{100.0, 0.5, -0.2, 1.0}}, kSpot, kRate, kDiv), InvalidInput);
        EXPECT_THROW(calibrate_heston({{100.0, 0.5, 0.2, 1.0}}, 0.0, kRate, kDiv), InvalidInput);
    }

} // namespace quantModeling
