/**
 * Palette validator — blueprint WP 01 §2.
 *
 * Checks the series palette from src/shared/styles/theme.css on both surfaces:
 *   - WCAG contrast of each series colour against the surface (target ≥ 3:1)
 *   - CIE76 ΔE between every adjacent pair, in normal vision and under
 *     protanopia / deuteranopia / tritanopia (Brettel-style severe simulation)
 *
 * Output is written to web/palette-report.txt so the check is replayable.
 * Run: node scripts/validate_palette.js
 */

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const themeCss = readFileSync(
	resolve(here, "../src/shared/styles/theme.css"),
	"utf8",
);

function palette(scopeRegex) {
	const block = themeCss.match(scopeRegex)?.[0] ?? "";
	const read = (name) =>
		block.match(new RegExp(`--color-${name}:\\s*(#[0-9a-fA-F]{6})`))?.[1];
	return {
		surface: read("surface"),
		series: [1, 2, 3, 4, 5, 6, 7, 8].map((i) => read(`series-${i}`)),
	};
}

const dark = palette(/@theme\s*\{[\s\S]*?\n\}/);
const light = palette(/\[data-theme="light"\]\s*\{[\s\S]*?\n\}/);

/* ── colour maths ─────────────────────────────────────────────────────── */
const srgbToLin = (c) => {
	c /= 255;
	return c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4;
};
const hexToRgb = (hex) => [
	parseInt(hex.slice(1, 3), 16),
	parseInt(hex.slice(3, 5), 16),
	parseInt(hex.slice(5, 7), 16),
];
const luminance = ([r, g, b]) =>
	0.2126 * srgbToLin(r) + 0.7152 * srgbToLin(g) + 0.0722 * srgbToLin(b);
const contrast = (a, b) => {
	const la = luminance(hexToRgb(a));
	const lb = luminance(hexToRgb(b));
	return (Math.max(la, lb) + 0.05) / (Math.min(la, lb) + 0.05);
};

function rgbToLab([r, g, b]) {
	const [lr, lg, lb] = [r, g, b].map(srgbToLin);
	let x = (lr * 0.4124 + lg * 0.3576 + lb * 0.1805) / 0.95047;
	let y = lr * 0.2126 + lg * 0.7152 + lb * 0.0722;
	let z = (lr * 0.0193 + lg * 0.1192 + lb * 0.9505) / 1.08883;
	const f = (t) => (t > 0.008856 ? Math.cbrt(t) : 7.787 * t + 16 / 116);
	[x, y, z] = [f(x), f(y), f(z)];
	return [116 * y - 16, 500 * (x - y), 200 * (y - z)];
}
const deltaE = (a, b) => {
	const la = rgbToLab(hexToRgb(a));
	const lb = rgbToLab(hexToRgb(b));
	return Math.hypot(la[0] - lb[0], la[1] - lb[1], la[2] - lb[2]);
};

// Severe CVD simulation matrices (Machado et al. 2009, severity 1.0).
const CVD = {
	protan: [
		[0.152286, 1.052583, -0.204868],
		[0.114503, 0.786281, 0.099216],
		[-0.003882, -0.048116, 1.051998],
	],
	deutan: [
		[0.367322, 0.860646, -0.227968],
		[0.280085, 0.672501, 0.047413],
		[-0.01182, 0.04204, 0.96978],
	],
	tritan: [
		[1.255528, -0.076749, -0.178779],
		[-0.078411, 0.930809, 0.147602],
		[0.004733, 0.691367, 0.3039],
	],
};
const simulate = (hex, m) => {
	const [r, g, b] = hexToRgb(hex).map(srgbToLin);
	const out = m.map((row) => row[0] * r + row[1] * g + row[2] * b);
	const lin2s = (c) => {
		c = Math.max(0, Math.min(1, c));
		return c <= 0.0031308 ? c * 12.92 : 1.055 * c ** (1 / 2.4) - 0.055;
	};
	return `#${out
		.map((c) =>
			Math.round(lin2s(c) * 255)
				.toString(16)
				.padStart(2, "0"),
		)
		.join("")}`;
};

/* ── run ──────────────────────────────────────────────────────────────── */
const lines = [];
let failed = false;
const log = (s) => lines.push(s);

for (const [name, p] of [
	["dark", dark],
	["light", light],
]) {
	log(`\n=== ${name}  surface ${p.surface} ===`);

	const contrasts = p.series.map((c) => contrast(c, p.surface));
	contrasts.forEach((ratio, i) => {
		const ok = ratio >= 3;
		if (!ok && name === "dark") failed = true;
		log(
			`  series ${i + 1} ${p.series[i]}  contrast ${ratio.toFixed(2)}:1  ${
				ok ? "PASS" : name === "dark" ? "FAIL" : "WARN (needs direct label)"
			}`,
		);
	});

	const adjacent = (list) => {
		let min = Infinity;
		for (let i = 0; i < list.length - 1; i++) {
			min = Math.min(min, deltaE(list[i], list[i + 1]));
		}
		return min;
	};

	const normalMin = adjacent(p.series);
	log(
		`  adjacent ΔE, normal vision   min ${normalMin.toFixed(1)}  ${normalMin >= 10 ? "PASS" : "FAIL"}`,
	);
	if (normalMin < 10) failed = true;

	for (const [cvd, m] of Object.entries(CVD)) {
		const sim = p.series.map((c) => simulate(c, m));
		const min = adjacent(sim);
		const ok = min >= 6;
		if (!ok) failed = true;
		log(
			`  adjacent ΔE, ${cvd.padEnd(7)}          min ${min.toFixed(1)}  ${ok ? "PASS" : "FAIL"}`,
		);
	}
}

const report =
	"palette validation — generated by scripts/validate_palette.js\n" +
	lines.join("\n") +
	`\n\noverall: ${failed ? "FAIL" : "PASS"}\n`;

writeFileSync(resolve(here, "../palette-report.txt"), report);
process.stdout.write(report);
process.exit(failed ? 1 : 0);
