#!/usr/bin/env python3
"""Generate include/quantModeling/utils/sobol_directions.hpp from the
Joe-Kuo new-joe-kuo-6.21201 direction-number file.

Usage:
    python3 scripts/gen_sobol_directions.py /tmp/new-joe-kuo-6.21201 1024

Source file: https://web.maths.unsw.edu.au/~fkuo/sobol/new-joe-kuo-6.21201
(S. Joe & F. Y. Kuo, "Constructing Sobol sequences with better
two-dimensional projections", SIAM J. Sci. Comput. 30, 2635-2654, 2008).

The header stores the primitive-polynomial data (s, a, m_i) compactly;
the 32 direction integers per dimension are expanded at runtime in
sobol.hpp (negligible cost, done once per simulation).
"""

import sys
from pathlib import Path

def main() -> None:
    src = Path(sys.argv[1] if len(sys.argv) > 1 else "/tmp/new-joe-kuo-6.21201")
    max_dim = int(sys.argv[2]) if len(sys.argv) > 2 else 1024

    s_list: list[int] = []
    a_list: list[int] = []
    m_flat: list[int] = []
    m_offset: list[int] = []

    with src.open() as f:
        next(f)  # header line "d s a m_i"
        for line in f:
            parts = line.split()
            if not parts:
                continue
            d = int(parts[0])
            if d > max_dim:
                break
            s, a = int(parts[1]), int(parts[2])
            m = [int(x) for x in parts[3:]]
            assert len(m) == s, f"dim {d}: expected {s} m-values, got {len(m)}"
            m_offset.append(len(m_flat))
            s_list.append(s)
            a_list.append(a)
            m_flat.extend(m)

    n = len(s_list)  # dimensions 2 .. n+1
    out = Path(__file__).resolve().parent.parent / \
        "include/quantModeling/utils/sobol_directions.hpp"

    def emit_array(name: str, ctype: str, values: list[int], per_line: int = 20) -> str:
        lines = [f"  inline constexpr {ctype} {name}[] = {{"]
        for i in range(0, len(values), per_line):
            chunk = ", ".join(str(v) for v in values[i:i + per_line])
            lines.append(f"      {chunk},")
        lines.append("  };")
        return "\n".join(lines)

    with out.open("w") as f:
        f.write(f"""#ifndef UTILS_SOBOL_DIRECTIONS_HPP
#define UTILS_SOBOL_DIRECTIONS_HPP

// AUTO-GENERATED by scripts/gen_sobol_directions.py — do not edit.
//
// Primitive polynomial data (s, a, m_i) for Sobol dimensions 2..{n + 1},
// from the Joe-Kuo file new-joe-kuo-6.21201 (SIAM J. Sci. Comput. 30,
// 2008). Dimension 1 (van der Corput) needs no data. Direction integers
// are expanded at runtime — see sobol.hpp.

#include <cstdint>

namespace quantModeling::sobol_detail
{{

  /// Highest supported dimension.
  inline constexpr int kMaxDimension = {n + 1};

  /// Degree s of the primitive polynomial, for dimensions 2..kMaxDimension
  /// (index d-2).
{emit_array("kS", "std::uint8_t", s_list, 40)}

  /// Encoded coefficients a of the primitive polynomial (index d-2).
{emit_array("kA", "std::uint32_t", a_list, 24)}

  /// Offset of each dimension's m-values inside kM (index d-2).
{emit_array("kMOffset", "std::uint32_t", m_offset, 20)}

  /// Initial direction values m_1..m_s, flattened.
{emit_array("kM", "std::uint32_t", m_flat, 24)}

}} // namespace quantModeling::sobol_detail

#endif // UTILS_SOBOL_DIRECTIONS_HPP
""")

    print(f"wrote {out} ({n} polynomial entries, {len(m_flat)} m-values)")

if __name__ == "__main__":
    main()
