#!/usr/bin/env python3
"""Generate the Sobol direction data from the Joe-Kuo new-joe-kuo-6.21201 file.

Usage:
    python3 scripts/gen_sobol_directions.py /tmp/new-joe-kuo-6.21201 [21201]

Source file: https://web.maths.unsw.edu.au/~fkuo/sobol/new-joe-kuo-6.21201
(S. Joe & F. Y. Kuo, "Constructing Sobol sequences with better
two-dimensional projections", SIAM J. Sci. Comput. 30, 2635-2654, 2008).

Writes two files:
  include/quantModeling/utils/sobol_directions.hpp  declarations only
  src/utils/sobol_directions.cpp                     the data, compiled once

The data are the primitive-polynomial triples (s, a, m_i); the 32 direction
integers per dimension are expanded at run time in sobol.hpp. All 21 201
dimensions (blueprint/wp/19-gpu.md §2.2): a daily one-year SLV path needs
2 factors x ~300 steps, and the Brownian bridge makes the high dimensions
nearly free -- but they must exist.
"""

import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def main() -> None:
    src = Path(sys.argv[1] if len(sys.argv) > 1 else "/tmp/new-joe-kuo-6.21201")
    max_dim = int(sys.argv[2]) if len(sys.argv) > 2 else 21201
    digest = hashlib.sha256(src.read_bytes()).hexdigest()

    s_list: list[int] = []
    a_list: list[int] = []
    m_flat: list[int] = []
    m_offset: list[int] = []

    with src.open() as f:
        next(f)  # header line "d s a m_i"
        for line in f:
            parts = line.split()
            if not parts:
                continue
            d = int(parts[0])
            if d > max_dim:
                break
            s, a = int(parts[1]), int(parts[2])
            m = [int(x) for x in parts[3:]]
            assert len(m) == s, f"dim {d}: expected {s} m-values, got {len(m)}"
            m_offset.append(len(m_flat))
            s_list.append(s)
            a_list.append(a)
            m_flat.extend(m)

    n = len(s_list)  # dimensions 2 .. n+1
    provenance = (
        f"// Primitive polynomial data (s, a, m_i) for Sobol dimensions 2..{n + 1},\n"
        "// from the Joe-Kuo file new-joe-kuo-6.21201 (SIAM J. Sci. Comput. 30,\n"
        f"// 2008), sha256 {digest}.\n"
        "// Dimension 1 (van der Corput) needs no data. Direction integers are\n"
        "// expanded at runtime -- see sobol.hpp.\n"
    )

    header = f"""#ifndef UTILS_SOBOL_DIRECTIONS_HPP
#define UTILS_SOBOL_DIRECTIONS_HPP

// AUTO-GENERATED by scripts/gen_sobol_directions.py -- do not edit.
//
{provenance}//
// The data live in src/utils/sobol_directions.cpp: {len(m_flat)} integers
// would otherwise be re-parsed by every translation unit including sobol.hpp.

#include <cstdint>

namespace quantModeling::sobol_detail
{{

    /// Highest supported dimension.
    inline constexpr int kMaxDimension = {n + 1};

    /// Degree s of the primitive polynomial, for dimensions 2..kMaxDimension
    /// (index d-2).
    extern const std::uint8_t kS[{n}];

    /// Coefficients a of the primitive polynomial (same indexing as kS).
    extern const std::uint32_t kA[{n}];

    /// Offset of dimension d's initial direction numbers in kM (index d-2).
    extern const std::uint32_t kMOffset[{n}];

    /// Initial direction numbers m_1..m_s, concatenated.
    extern const std::uint32_t kM[{len(m_flat)}];

}} // namespace quantModeling::sobol_detail

#endif // UTILS_SOBOL_DIRECTIONS_HPP
"""

    def emit(name: str, ctype: str, values: list[int], per_line: int = 24) -> str:
        rows = []
        for i in range(0, len(values), per_line):
            rows.append("        " + ", ".join(str(v) for v in values[i:i + per_line]))
        return f"    const {ctype} {name}[{len(values)}] = {{\n" + ",\n".join(rows) + "};\n"

    source = f"""// AUTO-GENERATED by scripts/gen_sobol_directions.py -- do not edit.
//
{provenance}
#include "quantModeling/utils/sobol_directions.hpp"

// clang-format off
namespace quantModeling::sobol_detail
{{

{emit("kS", "std::uint8_t", s_list)}
{emit("kA", "std::uint32_t", a_list)}
{emit("kMOffset", "std::uint32_t", m_offset)}
{emit("kM", "std::uint32_t", m_flat)}
}} // namespace quantModeling::sobol_detail
// clang-format on
"""

    (ROOT / "include/quantModeling/utils/sobol_directions.hpp").write_text(header)
    (ROOT / "src/utils/sobol_directions.cpp").write_text(source)
    print(f"{n + 1} dimensions, {len(m_flat)} direction numbers")


if __name__ == "__main__":
    main()
