#ifndef UTILS_SOBOL_DIRECTIONS_HPP
#define UTILS_SOBOL_DIRECTIONS_HPP

// AUTO-GENERATED by scripts/gen_sobol_directions.py -- do not edit.
//
// Primitive polynomial data (s, a, m_i) for Sobol dimensions 2..21201,
// from the Joe-Kuo file new-joe-kuo-6.21201 (SIAM J. Sci. Comput. 30,
// 2008), sha256 68eedd2a4e3b659b9695e7aff0f8ac68718bcf620730fc3d3a8c65df2a067441.
// Dimension 1 (van der Corput) needs no data. Direction integers are
// expanded at runtime -- see sobol.hpp.
//
// The data live in src/utils/sobol_directions.cpp: 354613 integers
// would otherwise be re-parsed by every translation unit including sobol.hpp.

#include <cstdint>

namespace quantModeling::sobol_detail
{

    /// Highest supported dimension.
    inline constexpr int kMaxDimension = 21201;

    /// Degree s of the primitive polynomial, for dimensions 2..kMaxDimension
    /// (index d-2).
    extern const std::uint8_t kS[21200];

    /// Coefficients a of the primitive polynomial (same indexing as kS).
    extern const std::uint32_t kA[21200];

    /// Offset of dimension d's initial direction numbers in kM (index d-2).
    extern const std::uint32_t kMOffset[21200];

    /// Initial direction numbers m_1..m_s, concatenated.
    extern const std::uint32_t kM[354613];

} // namespace quantModeling::sobol_detail

#endif // UTILS_SOBOL_DIRECTIONS_HPP
